version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: "redis1"
    networks:
      - docker_elk
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    depends_on:
      - redis
    links:
      - redis:redis1
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5044:5044"
    networks:
      - docker_elk
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
